<?php

?>
<p>Close the history books! It is time to get out and discover more about the people, places, and events that have shaped our lives, as well as our world. We are planning an educational and fun visit to <?php echo $data[0]['tou_destination']; ?>. </p>
<p>After careful consideration, we have selected Son-Tours, Inc. to plan and manage our trip. They are thorough, professional, and reasonably priced. Their staff is experienced and intimately familiar with our destination. Every detail has been executed to ensure a positive, safe, and worry-free learning environment for our children. </p>
<p>We plan to spend several days visiting various sites in <?php echo $data[0]['tou_destination']; ?>. Your tour price of &#36;<?php echo $data[0]['psc_full']; ?> based on minimum of <?php echo $data[0]['tou_capacity']; ?> paying people per coach(or &#36;<?php echo $data[0]['psc_minval1']+$data[0]['psc_full']; ?> based on a minimum of <?php echo $data[0]['psc_mincap1']; ?> paying people per coach, or &#36;<?php echo $data[0]['psc_minval2']+$data[0]['psc_full']; ?> based on <?php echo $data[0]['psc_mincap2']; ?> persons per coach, and &#36;<?php echo $data[0]['psc_minval3']+$data[0]['psc_full']; ?> is based on <?php echo $data[0]['psc_mincap3']; ?> persons per coach), includes the following: Roundtrip transportation, lodging, most meals, night-time hotel security, licensed tour guide, and all daily and evening activities! Our planned departure date will be on <?php echo date("m-d-Y", strtotime($data[0]['tou_start'])); ?>. We will return on <?php echo date("m-d-Y", strtotime($data[0]['tou_end'])); ?></p>
<p>The students will be accompanied by myself and adult chaperones throughout the trip. In addition, Son-Tours will have a staff member available to our group in <?php echo $data[0]['tou_destination']; ?> , and security personnel will be provided at our hotel each evening.</p>
<p>In order to reserve the itinerary we want, we will need to register for this tour as soon as possible. Bookings to this area are made months in advance of planned trips. Each of you should complete and return the enclosed enrollment form along with your deposit made out to Son-Tours by the due date listed on the form.</p>
<p>We sincerely hope that your child will be able to accompany us on this exciting trip. *For help with any accounting related matters, call Son-Tours Accounting Department customer assistance number (678)-325-2378.</p>
							        

